// Binding types are generated by `wrangler types`; secret bindings are deliberately not in config.
export interface ReviewEnv extends Env {
  DEVICE_TOKEN: string;
  SESSION_SECRET: string;
  MODEL_API_KEY?: string;
  MODEL_API_URL?: string;
  AI_MODEL?: string;
}
export type Role = "admin" | "operator";
export interface User {
  id: string;
  username: string;
  role: Role;
}
export interface Option {
  value_id: string;
  label: string;
  position: number;
}
export type DeviceEventType =
  | "product.upsert"
  | "snapshot.created"
  | "checkpoint.updated"
  | "stage.completed"
  | "readback.recorded"
  | "review.created"
  | "text_facts.created";
export type Json =
  string | number | boolean | null | Json[] | { [key: string]: Json };
export interface DeviceEventInput {
  idempotency_key: string;
  event_type: DeviceEventType;
  payload: Record<string, Json>;
}
export interface ReviewTask {
  id: string;
  run_id: string;
  device_id: string;
  product_version: string;
  platform_id: string;
  category_leaf_id: string;
  field_id: string;
  field_label: string;
  canonical_field: string | null;
  snapshot_version: string;
  suggested_value_id: string | null;
  status: string;
  reason_code: string;
  evidence_json: string;
  claimed_by: string | null;
  lease_until: string | null;
  version: number;
}
