const styles = `:root{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:#1d1d1f;background:#f5f5f7;font-synthesis:none}*{box-sizing:border-box}body{margin:0}main{max-width:1000px;margin:52px auto;padding:0 24px}header{display:flex;justify-content:space-between;align-items:center;margin-bottom:24px}header p{color:#6e6e73;font-size:14px}h1{font-size:26px;letter-spacing:-.6px;font-weight:600}.card{background:white;border-radius:24px;padding:32px;box-shadow:0 8px 40px #00000006}.layout{display:grid;grid-template-columns:1fr 1fr;gap:36px}.photo{width:100%;aspect-ratio:4/5;object-fit:contain;background:#f8f8fa;border-radius:16px}h2{font-size:25px;margin:8px 0 20px}.label{font-size:13px;color:#6e6e73;margin:20px 0 8px}.suggestion{font-size:20px;font-weight:600}.options{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin:20px 0}button,input,select{font:inherit}button{cursor:pointer;border:1px solid #d2d2d7;border-radius:12px;padding:13px 18px;background:#fff;color:#1d1d1f}button[aria-pressed=true]{border:2px solid #0071e3;background:#f0f7ff;padding:12px 17px}button:disabled{opacity:.45;cursor:default}.primary{background:#0071e3;color:white;border-color:#0071e3}.actions{display:flex;gap:12px;justify-content:flex-end;margin-top:28px;border-top:1px solid #eee;padding-top:24px}summary{cursor:pointer;color:#0066cc;padding:14px 0}details p{font-size:14px;line-height:1.7;color:#515154}input,select{display:block;width:100%;padding:12px;border:1px solid #ccc;border-radius:9px;margin:8px 0 16px}label{font-size:14px}:focus-visible{outline:3px solid #0071e3;outline-offset:4px}.status{min-height:24px;color:#a53a22;font-size:14px;margin-top:16px}#login{max-width:420px;margin:60px auto}#empty{text-align:center;padding:60px 10px;color:#6e6e73}[hidden]{display:none!important}@media(max-width:700px){main{margin:20px auto;padding:0 16px}.card{padding:20px}.layout{grid-template-columns:1fr;gap:16px}.photo{aspect-ratio:1;max-height:360px}.actions{justify-content:stretch}.actions button{flex:1}h1{font-size:22px}}`;
export function reviewPage(authenticated: boolean): Response {
  const html = `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>商品属性审核</title><link rel="stylesheet" href="/app.css"><script src="/app.js" defer></script></head><body data-authenticated="${authenticated}"><main><header><h1>商品属性审核</h1><p id="progress">一次专注一个判断</p></header><section id="login" class="card" ${authenticated ? "hidden" : ""}><h2>登录审核中心</h2><form id="login-form"><label>用户名<input name="username" autocomplete="username" required maxlength="128"></label><label>密码<input name="password" type="password" autocomplete="current-password" required maxlength="1024"></label><button class="primary" type="submit">登录</button></form></section><section id="review" class="card" hidden><div class="layout"><div><img class="photo" id="product-image" alt="待审核商品图"><p id="image-note"></p></div><div><p class="label" id="platform"></p><h2 id="product-title"></h2><p class="label">字段名称</p><h2 id="field-name"></h2><p class="label">AI 建议</p><p class="suggestion" id="suggestion"></p><div id="options" class="options" role="group" aria-label="可选属性值"></div><template id="candidate-template"><button type="button" data-value-id="" aria-pressed="false"></button></template><label id="reason-label" hidden>改选原因<select id="reason"><option value="">请选择原因</option><option>图片证据与建议不符</option><option>文字资料与建议不符</option><option>候选映射不准确</option><option>需要人工纠正</option></select></label><details><summary>查看判断依据与相似商品</summary><p id="evidence"></p><p id="similar">暂无经保存回读验证的相似商品。</p></details></div></div><div class="actions"><button id="skip" type="button">暂时跳过</button><button id="confirm" class="primary" type="button" disabled>确认并继续</button></div></section><section id="empty" class="card" hidden>当前没有可处理的审核任务。<p><button id="refresh" type="button">刷新待审任务</button></p></section><p id="status" class="status" role="status" aria-live="polite"></p></main></body></html>`;
  return new Response(html, {
    headers: {
      "content-type": "text/html; charset=utf-8",
      "cache-control": "no-store",
      "content-security-policy":
        "default-src 'none'; script-src 'self'; style-src 'self'; img-src 'self'; connect-src 'self'; base-uri 'none'; form-action 'self'; frame-ancestors 'none'",
      "referrer-policy": "no-referrer",
      "x-content-type-options": "nosniff",
    },
  });
}
export const uiStyles = styles;
export const uiScript = String.raw`'use strict';
const $=id=>document.getElementById(id);let current=null,selected=null,busy=false,leaseAt=0,lastActive=Date.now();const skipped=new Set();
function message(value){$('status').textContent=value;}
function lock(value){busy=value;$('confirm').disabled=value||!selected;$('skip').disabled=value;document.querySelectorAll('[data-value-id],#reason').forEach(el=>el.disabled=value);}
async function api(path,data){const response=await fetch(path,{method:data===undefined?'GET':'POST',credentials:'same-origin',headers:{'content-type':'application/json'},body:data===undefined?undefined:JSON.stringify(data)});if(!response.ok){if(response.status===409)throw Error('任务已被其他运营更新，请刷新待审任务。');if(response.status===401)throw Error('登录已过期，请刷新页面重新登录。');if(response.status===422)throw Error('请检查候选值与改选原因。');throw Error('暂时无法完成，请稍后重试。');}return response.json();}
function render(task){$('review').hidden=false;$('empty').hidden=true;$('product-title').textContent=task.title;$('platform').textContent=task.platform_id;$('field-name').textContent=task.field_label;selected=task.options.some(o=>o.value_id===task.suggested_value_id)?task.suggested_value_id:null;$('suggestion').textContent=task.options.find(o=>o.value_id===selected)?.label||'需要人工判断';$('options').replaceChildren();for(const option of task.options){const button=document.createElement('button');button.type='button';button.dataset.valueId=option.value_id;button.textContent=option.label;button.setAttribute('aria-pressed',String(selected===option.value_id));button.onclick=()=>{selected=option.value_id;lastActive=Date.now();document.querySelectorAll('[data-value-id]').forEach(el=>el.setAttribute('aria-pressed',String(el.dataset.valueId===selected)));$('reason-label').hidden=selected===task.suggested_value_id;lock(false);};$('options').append(button);}$('reason').value='';$('reason-label').hidden=true;const image=$('product-image');if(task.asset_ids.length){image.src='/api/assets/'+encodeURIComponent(task.asset_ids[0]);image.hidden=false;$('image-note').textContent='';image.onerror=()=>{image.hidden=true;$('image-note').textContent='商品图暂不可用，请核对判断依据。';};}else{image.removeAttribute('src');image.hidden=true;$('image-note').textContent='尚未上传商品图。';}const evidence=task.evidence;$('evidence').textContent=typeof evidence.summary==='string'?evidence.summary:'本项需要人工确认，请结合商品图片与当前候选值判断。';lock(false);$('field-name').tabIndex=-1;$('field-name').focus();}
async function next(){message('');lock(true);try{const {tasks}=await api('/api/reviews');const task=tasks.find(t=>!skipped.has(t.id));if(!task){current=null;$('review').hidden=true;$('empty').hidden=false;$('progress').textContent='待审任务已处理或暂时跳过';return;}const claimed=await api('/api/reviews/'+encodeURIComponent(task.id)+'/claim',{version:task.version});current={...task,...claimed};leaseAt=Date.now();$('progress').textContent='还有 '+tasks.length+' 项待判断';render(current);}catch(error){message(error.message);$('empty').hidden=false;}finally{lock(false);}}
async function submit(action){if(busy||!current)return;if(action==='confirm'&&selected!==current.suggested_value_id&&!$('reason').value){message('改选候选后，请选择纠正原因。');$('reason').focus();return;}lock(true);try{await api('/api/reviews/'+encodeURIComponent(current.id)+'/'+action,{version:current.version,...(action==='confirm'?{final_value_id:selected,...($('reason').value?{correction_reason:$('reason').value}:{})}:{})});if(action==='skip')skipped.add(current.id);current=null;await next();}catch(error){message(error.message);}finally{lock(false);}}
$('confirm').onclick=()=>submit('confirm');$('skip').onclick=()=>submit('skip');$('refresh').onclick=()=>{skipped.clear();next();};
$('login-form').onsubmit=async event=>{event.preventDefault();const button=event.target.querySelector('button');button.disabled=true;try{const data=new FormData(event.target);await api('/api/login',{username:data.get('username'),password:data.get('password')});location.reload();}catch{message('登录失败，请检查用户名和密码。');}finally{button.disabled=false;}};
document.addEventListener('pointerdown',()=>lastActive=Date.now());document.addEventListener('keydown',()=>lastActive=Date.now());
setInterval(async()=>{if(!current||busy||document.hidden||Date.now()-lastActive>120000||Date.now()-leaseAt<300000)return;lock(true);try{const renewed=await api('/api/reviews/'+encodeURIComponent(current.id)+'/renew',{version:current.version});current={...current,...renewed};leaseAt=Date.now();}catch(error){message(error.message);}finally{lock(false);}},60000);
if(document.body.dataset.authenticated==='true')next();
`;
