/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 9098379ed1f42655bf978b254ddf2fdf)
interface __BaseEnv_Env {
	ASSETS: R2Bucket;
	DB: D1Database;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
